name: flutter_native_string_res
description: Flutter plugin for getting native string resources on Android and iOS
version: 0.0.1+2
author: rafern <rafern@protonmail.com>
homepage: https://github.com/rafern/flutter_native_string_res

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutter.flutter_native_string_res
    pluginClass: FlutterNativeStringResPlugin
