name: flutter_native_string_res
description: Flutter plugin for gettings native string resources
version: 0.0.1
author: rafern
homepage: https://github.com/rafern/flutter_native_string_res

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutter.flutter_native_string_res
    pluginClass: FlutterNativeStringResPlugin
